// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc6413.PowerUp;

import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.XboxController;
import edu.wpi.first.wpilibj.buttons.*;

import org.usfirst.frc6413.PowerUp.commands.*;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    //// CREATING BUTTONS
    // One type of button is a joystick button which is any button on a joystick.
    // You create one by telling it which joystick it's on and which button
    // number it is.
    // Joystick stick = new Joystick(port);
    // Button button = new JoystickButton(stick, buttonNumber);

    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.

    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:

    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());

    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());

    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());

	public XboxController driveJoystick;
	public XboxController armJoystick;

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    public JoystickButton shifterButton; 
    public JoystickButton shifterButtonBack;
    
    public JoystickButton testButton;
    
    public DigitalInput armTrigger;
    
    public GearSensorDigitalSwitch gearSwitch;
    
    private boolean shifted = true;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public OI() {
    	driveJoystick = new XboxController(0);
    	armJoystick = new XboxController(1);
    	
    	shifterButton = new JoystickButton(driveJoystick, 6);
    	shifterButton.whenPressed(new ShiftLowGear());
    	
    	shifterButtonBack = new JoystickButton(driveJoystick, 5);
    	shifterButtonBack.whenPressed(new ShiftHighGear());
    	
    	//1/20/2018 Update
    	/*if(!shifted) {
    		shifted = true;
        	shifterButton.whenPressed(new ShiftLowGear());
    	} else {
    		shifted = false;
        	shifterButton.whenPressed(new ShiftHighGear());
    	} */
    	
    	
    	
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        
       
        
        //testButton = new JoystickButton(driveJoystick, 1);
        //testButton.whenPressed(new TestDriveCount());
        

        
        
        // SmartDashboard Buttons
        SmartDashboard.putData("Autonomous Command", new AutonomousCommand());
        SmartDashboard.putData("Mecanum Drive", new MecanumDriveClass());



    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        
        /* xbox button mapping
         * A = 1
         * B = 2
         * X = 3
         * Y = 4
         * leftStick press = 9
         * rightStick press = 10 
         * backButton = 7
         * startButton = 8
         * leftBumper = 5
         * rightBumper = 6
         */
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public XboxController getDriveJoystick() {
        return driveJoystick;
    }

}

