// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc6413.SteamWorks.commands;
import edu.wpi.first.wpilibj.GenericHID.RumbleType;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc6413.SteamWorks.Robot;

/**
 *
 */
public class JawsClose extends Command {

	private boolean armIsOpen = true;
	private long closeTime;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public JawsClose() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.arm);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	setTimeout(.5);
    	if(armIsOpen) {
    		Robot.arm.closeArm();
    		Robot.oi.driveJoystick.setRumble(RumbleType.kLeftRumble, 1);
    		Robot.oi.armJoystick.setRumble(RumbleType.kLeftRumble, 1);
    		
    		closeTime = System.currentTimeMillis();
    		System.out.println("close timestamp: " + closeTime);
    	} else {
    		Robot.arm.openArm();
    	}  
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	  	
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() { 
    	
        return isTimedOut();
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.oi.driveJoystick.setRumble(RumbleType.kLeftRumble,0);
		Robot.oi.armJoystick.setRumble(RumbleType.kLeftRumble, 0);
    	armIsOpen = !armIsOpen;
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	
    }
}
